flask-rest1:
  build: .

  volumes:
    - .:/code

  links:
    - mongodb

  ports:
    - "5000:5000"

mongodb:
  image: mongo

  volumes:
    - "/srv/data/db:/data/db:rw"
  ports:
    - "27017:27017"

